source_dir = "src/c"
file_extension = "c"
global_field = "static $field_type $label;"

[condition.depth]
appconfig_depthfmt = "\n\t.createDepthFormat = $depth_format,"
depth_info_ref = "&depthInfo"
lesson_struct_depth = """
	const SDL_GPUDepthStencilTargetInfo depthInfo =
	{
		.texture = ctx->depthTexture,
		.clear_depth = 1.0f,  // Ensure depth buffer clears to furthest value
		.load_op = SDL_GPU_LOADOP_CLEAR,
		.store_op = SDL_GPU_STOREOP_DONT_CARE,
		.stencil_load_op = SDL_GPU_LOADOP_DONT_CARE,
		.stencil_store_op = SDL_GPU_STOREOP_DONT_CARE,
		.cycle = true
	};
"""

[condition.-depth]
depth_info_ref = "NULL"

[condition.projection]
lesson_func_resize = """

static void Lesson${lesson_num}_Resize(NeHeContext* restrict ctx, int width, int height)
{
	(void)ctx;

	// Avoid division by zero by clamping height
	height = SDL_max(height, 1);
	// Recalculate projection matrix
	projection = Mtx_Perspective(45.0f, (float)width / (float)height, 0.1f, 100.0f);
}
"""

[condition.key]
appconfig_resize = "Lesson${lesson_num}_Resize"
appconfig_key = ",\n\t.key = Lesson${lesson_num}_Key"
lesson_func_key = """

static void Lesson${lesson_num}_Key(NeHeContext* ctx, SDL_Keycode key, bool down, bool repeat)
{
	(void)ctx;

	if (down && !repeat)
	{
		switch (key)
		{
		default:
			break;
		}
	}
}
"""

[condition.-key]
appconfig_resize = "NULL"
